import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";

import { Navbar } from "@/components/navbar_user";
import { ROLE_COOKIE_NAME, normalizeRole } from "@/lib/auth";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const roleValue = cookieStore.get(ROLE_COOKIE_NAME)?.value;
  const role = normalizeRole(roleValue) || null;

  return (
    <html lang="en" className={`${poppins.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Navbar initialRole={role}>{children}</Navbar>
      </body>
    </html>
  );
}
